version: '3.8'

services:
  # db
  postgre_db:
    container_name: postgredb
    image: postgres:15
    ports:
      - "2004:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: TradingEngineDB

  # spring server
  spring_app:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgre_db:5432/TradingEngineDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgre_db
      - python_api

  # python API
  python_api:
    build:
      context: matching-engine
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
