services:
  #db
  postgre_db:
    container_name: postgredb
    image: postgres:15
    ports:
      - "2004:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: TradingEngineDB
  #server
  spring_app:
    build:
      context: server
      dockerfile: src/Dockerfile # jar-ul compilat
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgre_db:5432/TradingEngineDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    #ca sa fim siguri ca baza de date e incarcata ianinte de spring app
    depends_on:
      - postgre_db
